apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::229993840607:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8OZB944EFNC0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::229993840607:role/UdacityFlaskDeployCBKubectlRole1
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-20T23:37:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1369"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ca565736-3bbc-4011-85a2-597b70e8cec5
